### ISSUE TITLE
(Node 8.16.x) SyntaxError: Unexpected token { ...

### ISSUE THREAD

**Issue by moos** [FlorianRappl/parcel-plugin-externals#17]
I'm seeing this error in version 0.4.1 and node 8.16.x: 

```
  Plugin parcel-plugin-externals failed to initialize: /foo/node_modules/parcel-plugin-externals/utils.js:137
  } catch {
          ^

SyntaxError: Unexpected token {
    at NativeCompileCache._moduleCompile (/foo/node_modules/v8-compile-cache/v8-compile-cache.js:242:18)
    at Module._compile (/foo/node_modules/v8-compile-cache/v8-compile-cache.js:186:36)
...
```
Looks like that should be `catch () {...`.  Works in Node 10.16.x.

**Comment by FlorianRappl** [comment]
Thanks for catching this!
